### PR TITLE
add package-lock.json to gitignore

### PR DESCRIPTION
**Pull request by nileshgulia1**
We don't need to commit this everytime, this will allow us to always test the latest version of our dependencies especially in CI.

### CODE REVIEW

**Comment by AnshulMalik** [comment]
I believe package-lock should be kept in the repo. https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

**Comment by yurydelendik** [comment]
> I believe package-lock should be kept in the repo.

I agree. There are two lines of thoughts: keep package-lock.json or not. In our case, it will be beneficial to keep entire tool set and referred packages on the same version on every computer to reproduce the same built code. That said, any change to the package-lock.json shall be considered as library/dependency upgrade, therefore the change deserves a separate PR IHMO

**Comment by mbebenita** [comment]
I agree with @yurydelendik, any time we upgrade our dependencies we need to test manually.

**Comment by nileshgulia1** [comment]
@AnshulMalik  @yurydelendik  @mbebenita  Its better closing it then :)

**Pull request closed without merging**
