### PR TITLE
TextEncoder fix

### PR DESCRIPTION
**Pull request by haxxorsid**
I don't know what is the use of util.ts, but this is the fix to its error.

I am struggling to compile project properly in order to perform some changes.

### CODE REVIEW

**Comment by mbebenita** [comment]
Thanks!

`TextEncoder` should be supported natively in Chrome and Firefox. The NPM package you included is a polyfill that's not necessary. You can probably just get away with declaring the TextEncoder as any to get around the type system and avoid having to take on a dependency on `text-encoding` module.

Are you getting any other compiler errors? I see there's one in `Test.tsx` that I should fix.

**Comment by haxxorsid** [comment]
Yeah correct. But at least:
This should be replaced:
`var bytes = new TextEncoder('utf-8').encode(buffer);`
With this:
`var bytes = new TextDecoder('utf-8').decode(buffer);`
In order to solve: **TS2345**
Because we are converting ArrayBuffer to String, encode accepts only String.

**Comment by haxxorsid** [comment]
For WasmParser error: wasdk/wasmparser@f9f3afb65eb3a74be8ee6b5e7f89768bd35b5677

**Comment by mbebenita** [comment]
Oh, I just realized from your comment that base64Encode is not even being used yet, feel free to remove it for now, and we can add it back in later when we need it.

**Comment by mbebenita** [comment]
I think this is no longer necessary, fixed by other commits. Closing this PR.

**Pull request closed without merging**
